### ISSUE TITLE
As a TFF staff, I want to be able to assign referees to matches from fixture matches on the fixture page so I will be able to change the assigned referee to a match.

### ISSUE THREAD

**Issue by egemetin27** [SU-CS308-22FA/CS_308_Team3#30]
RGB: As a TFF staff, I want to be able to assign referees to matches from fixture matches on the fixture page so I will be able to change the assigned referee to a match. 

Acceptance Criteria: 
I can see available referees for a given match.
I can select one of the referees.
I can change assigned referee

**Comment by MehmetCandar** [comment]
a pull request has been opened to merge the finalized "assign referee" page.

log in as TFF staff and you will be able to assign referees to matches through its fixture page
